#!/bin/bash

# Author: Paul Marks
# Date: December 2021

# fim: Searches from the current or a specified directory for a file, opens the file in vim if it 

# is found.

# exit 1: usage error
# exit 2: invalid file option

## check for at least one, but no more than two command line arguments.
if [[ "$#" -lt 1 ]]; then
    echo "Usage: fim [directory] <filename>"
    exit 1
fi
if [[ "$#" -gt 2 ]]; then
    echo "Usage: fim [directory] <filename>"
    exit 1
fi

getOption () {
    read -rp "$1" num
    re='^[+-]?[0-9]+$'
    if ! [[ $num =~ $re ]]; then
        getOption "NAN, try again > "
    elif [[ $num -ge ${#matches[@]} ]]; then
        getOption "Invalid option, try again > "
    elif [[ $num -lt 0 ]]; then 
        true
    else
        vim "${matches[$num]}"
    fi
}

## if one command line argument.
if [ "$#" -eq 1 ]; then
    file="$1"

    #find ./ -name "$file" -exec vim {} \; 2>/dev/null
    #find ./ -name "$file" 2>/dev/null | | grep -q "$file"
    #find ./ -name "$file" -exec vim {} \; 2>&1 | grep -v "Permission denied"

    find ./ -name "$file" 2>&1 | grep -v "Permission denied" | grep -q "$file"
    code="$?"
    if [[ "$code" -eq 0 ]]; then
        matches=()
        for line in $(find ./ -name "$file" 2>&1 | grep -v "Permission denied"); do
            matches+=($line)
            #vim "$line"
        done
        count=0
        for match in "${matches[@]}"; do
            echo "$count) $match"
            ((count++))
        done
        getOption "Which file do you want to open? > "
        code="$num"
    fi
fi

## if two command line arguments.
if [ "$#" -eq 2 ]; then
    file="$2"

    #find "$1" -name "$file" -exec vim {} \; 2>/dev/null
    #find "$1" -name "$file" 2>/dev/null | grep -q "$1"
    #find "$1" -name "$file" -exec vim {} \; 2>&1 | grep -v "Permission denied"

    find "$1" -name "$file" 2>&1 | grep -v "Permission denied" | grep -q "$file"
    code="$?"
    if [[ "$code" -eq 0 ]]; then
        for line in $(find "$1" -name "$file" 2>&1 | grep -v "Permission denied"); do
            #vim "$line"
            matches+=($line)
        done
        count=0
        for match in "${matches[@]}"; do
            echo "$count) $match"
            ((count++))
        done
        getOption "Which file do you want to open? > "
        code="$num"
    fi
fi

if [[ "$code" -ne 0 ]]; then
    echo -n "File was not found, would you like to create file $file? (y/n) "
    read answer
    if [[ "$answer" == "y" ]]; then
        echo
        ini.sh "$file"
        if [[ "$?" -ne 0 ]]; then
            touch "$file"
        fi
    fi
fi
