#!/bin/bash

##initialize a java file

#exit 1: usage error

##if no command line args
if [ $# -lt 1 ]; then
    echo "Usage: inijava <file>"
    exit 1
fi

file="$1"

##create a message for the javadoc
read -rp "Description for $file > " mess
message+="\n"

##set up variables

#class name is everything before extension
cname=${file%.*}

dt=`date '+%B %Y'`
tab="    "

##create/initialize file
printf "/**\n * $mess\n * \n * @author $NAME\n * @version $dt\n */\n" > $file
printf "\npublic class $cname {\n" >> $file
printf "\n$tab" >> $file
printf "public $cname() {\n" >> $file
printf "$tab}\n" >> $file
printf "}\n" >> $file
