#!/bin/bash

# Author: Paul Marks
# Date: December 2021

# inish: Initialize a bash script file

# exit 1: usage error

## if no command line args
if [ $# -lt 1 ]; then
    echo "Usage: inish <file>"
    exit 1
fi

file="$1"

## set up a message for class description
read -rp "Description for $file > " mess

## variable setup

# class name is everything before file extension
cname=${file%.*}

dt=`date '+%B %Y'`
tab="    "

## create/initialize file
printf "#!/bin/bash\n\n" > $file
printf "# Author: $NAME\n" >> $file
printf "# Date: $dt\n\n" >> $file
printf "# $cname: $mess\n" >> $file
printf "# exit 1: usage error\n\n" >> $file
