#!/bin/bash

##initialize a MIPS 32 file

#exit 1: usage error

##if no command line args
if [ $# -lt 1 ]; then
    echo "Usage: inis <file>"
    exit 1
fi

file="$1"

##set up a message for class description
read -rp "Description for $file > " mess

##variable setup

#class name is everything before file extension
cname=${file%.*}

dt=`date '+%B %Y'`
tab="    "

##create/initialize file
printf "# $cname\n" > $file
printf "# Author: $NAME\n" >> $file
printf "# Date: $dt\n" >> $file
printf "#\n# $mess\n" >> $file
printf "\n# ----- Data Segment -----\n" >> $file
printf "$tab.data\n" >> $file
printf "nl:$tab$tab$tab.byte 10 0\n\n" >> $file
printf "\n# ----- Text Segment -----\n" >> $file
printf "$tab.text\n" >> $file
printf "main:\n\n" >> $file
printf "$tab### \n\n\n" >> $file
printf "$tab""li \$v0, 10\n" >> $file
printf "$tab""syscall" >> $file
