#!/bin/bash

# Author: Paul Marks
# Date: December 2021

# taz: Tar a file without having to remember the options.

# exit 1: usage error

## no command line args
if [[ $# -lt 1 ]]; then
    echo "Usage: tabz [OPTIONS] <file>"
    exit 1
fi

hlp () {
    ## display the help menu
    echo "tabz, Make tar easier"
    echo -e "\nUSAGE:"
    echo -e "\ttabz [OPTIONS] <file>" | expand -t4
    echo -e "\nOPTIONS:" | expand -t4
    echo -e "\t-h, --help\t\t\tDisplay this menu and exit" | expand -t4
    echo -e "\t\t--list\t\t\tList all options" | expand -t4
    echo -e "\n\t-n\t\t\t\t\tName the tar file" | expand -t4
}

## no options present
if [[ $# -eq 1 ]]; then
    file="$(echo $1 | sed 's/\///')"
fi

##  if an option is present
if [[ ${1:0:1} == "-" ]]; then

    case $1 in
        -n)
            shift
            file=$1
            shift
            ;;

        -h)
            hlp
            exit 0
            ;;

        --help)
            hlp
            exit 0
            ;;

        --list)
            echo "[-n] [-h, --help] [--list]"
            exit 0
            ;;

        *)
            echo "tabz: invalid option -- $1"
            exit 1
            ;;
    esac
fi

tar -cvjf "$file".tbz $1
